config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_attached_file :image, styles:  { medium: "300x300>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :find_pin, only: [:show,:edit,:update,:destroy,:upvote]
    # before_action :pin_auth, only: [:show,:edit, :update, :destroy,:upvote]
    before_action :authenticate_user!, except: [:index,:show]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def new
		@pin = current_user.pins.build
	end
 
	def show 
	end


	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin,notice:"Successfully created"
		else
			render 'new'
		end
	end

	def edit
	end


	def update
		if @pin.update(pin_params)
			redirect_to @pin,notice:"Pin was successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end



	private 

	def pin_params
       params.require(:pin).permit(:title, :description, :image)
    end

    def pin_auth
        if current_user !=@pin.user
        redirect_to(root_path)
        end
    end

    def find_pin
    	@pin=Pin.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PinBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default"> 
    <div class="container-fluid">
    	<div class="navbar-brand"><%=link_to "Pin Board" ,root_path%>
    	</div>

    		
    		<%if user_signed_in?%>
    		<ul class="nav navbar-nav navbar-right">
    			<li><%=link_to "New Pin",new_pin_path %></li>
    			<li><%=link_to "Account",edit_user_registration_path %></li>
    			<li><%=link_to "Sign Out",destroy_user_session_path, method: :delete%></li>
    		</ul>
    		<% else %>
    		<ul class="nav navbar-nav navbar-right">
    			<li><%=link_to "Sign Up",new_user_registration_path %></li>
    			<li><%=link_to "Sign In",new_user_session_path%></li>
    			</nav>
    		</ul>
    		<%end%>
    	</div>
    </div>
</nav>
<div class="container-fluid">
    <% flash.each do |name,msg| %>
       <%= content_tag :div, msg, class: "alert alert-info" %>
   <%end%>

</div>



<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<%=simple_form_for @pin, remote: true,:html => {:multipart =>true} ,authenticity_token: true  do |f| %>

    <% if @pin.errors.any? %>
	   
		<div id ='errors'>
		<h2>
		<%=pluralize(@pin.errors.count,"error")%>
		prevented this pin from saving

		</h2>
		<ul>
		
		<% @pin.errors.full_messages.each  do |msg| %>
		<li> <%=msg%> </li>
		<%end%>
		<%end%>
	
		</ul>
		</div>

    <div class="form_group">
	<%= f.input :image , input_html: {class: 'form-control'} %>
	</div>
	<br>
   

    <div class="form_group">
	<%= f.input :title , input_html: {class: 'form-control'} %>
	</div>
	<br>

	<div class="form_group">
	<%= f.input :description , input_html: {class: 'form-control'} %>
	<br>

	<%=f.button :submit, class: "btn btn-primary" %>
	</div>
    

<%end%>

app/views/pins/edit.html.erb
<h1>
	Edit pin
</h1>
<%=image_tag @pin.image.url(:medium )%>
<%= render 'form'%>
<%= link_to "Cancel", pin_path%>



<!-- <div class="col-md-6 col-md-offset-3">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1> Edit Pin</h1>
			</div>
		    <div class="panel-body">
			    <strong>Current Image</strong>
			    <br>
		    		<%=image_tag @pin.image.url(:medium )%>
		    	<br>
		    	<%=render 'form' %>
		    </div>
		    </div>
	</div>		
</div> -->

app/views/pins/index.html.erb
<div id ="pins" class="transitions-enabled">
	<% @pins.each do |pin| %>
		<div class="box">
			<div class="panel panel-default">
				<%= link_to (image_tag pin.image.url),pin %>
				<h2>
					<%=link_to pin.title,pin %>
				</h2>
				<p class="user">
					Submitted By:
					<%=pin.user.email%>
				</p>
			</div>
		</div>
		<div class="panel-body">
				
			<%end%>
		</div>
	</div>

app/views/pins/new.html.erb
<h1> 
	New form
</h1>
<%=render 'form' %>
<%=link_to "Back",root_path %>



<!-- 
<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1> New Pin</h1>
			</div>
		    <div class="panel-body">
		    	<%=render 'form' %>
		    </div>
		    </div>
	</div>		
</div> -->

app/views/pins/show.html.erb
<div id="pin_show" class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading pin_image">
				<%=image_tag @pin.image.url(:medium)%>
			</div>
			<div class="panel-body">
				<h1>
					<%=@pin.title%>
				</h1>
				<p class="description">
					<%=@pin.description%>
				</p>
				Submitted By:
				<%=@pin.user.email%>
				<br>
			</div>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6 ">
						<p class="user">
							Submitted By:
							<%=@pin.user.email%>
						</p>
						<div class="col-md-6 ">
							<div class="btn-group pull-right">

								<button type="btn-btn default">
									<%=link_to like_pin_path(@pin),method: :put  do%>
										<span class="glyphicon glyphicon-heart">
											<%=@pin.get_upvotes.size%>
										<%end%>
										
									</span>
	
								</button>

								<% if user_signed_in? %>
									<button type="btn-btn default">
										<%=link_to "Edit",edit_pin_path%>
									</button>
									<button type="btn-btn default">
											<%=link_to "Delete",pin_path, method: :delete , data: { confirm: "Are you sure?" }%>
										</button>
								<%end%>
									
								</div>
						</div>
						
					</div>
				</div>
				
			</div>
			
		</div>
	</div>

</div>